[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.1.0"
description = "{{ cookiecutter.description }}"
readme = "README.md"
authors = [{ name = "{{ cookiecutter.author_name }}" }]
requires-python = ">={{ cookiecutter.python_version }}"
dependencies = [
    "python-dotenv",
    "loguru"
]

[project.scripts]
"{{ cookiecutter.project_slug }}" = "src.main:main"

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "pre-commit",
]

[tool.ruff]
line-length = 100
target-version = "py{{ cookiecutter.python_version.replace('.', '') }}"

[tool.ruff.lint]
select = [
    "E",   # Style errors (pycodestyle)
    "F",   # Logic errors (pyflakes)
    "I",   # Import sorting (isort)
    "UP",  # Deprecated Python syntax (pyupgrade)
    "B",   # Likely bugs (flake8-bugbear)
]
fixable = ["ALL"] # Allow ruff to auto-fix everything it can